<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="article_management.aspx.cs" Inherits="lifeInsurance.article_management" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Admin Panel | Article Management </title>
    <link href="css/main.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="wrapper">
        <div class="content">
            <br />
            <br />
            <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" BackColor="White" TabIndex="-1" Font-Size="Small" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" Font-Bold="False">
                <asp:ListItem Value="0">MANAGE ARTICLES</asp:ListItem>
                <asp:ListItem Value="1">UPLOAD ARTICLES</asp:ListItem>
            </asp:DropDownList>
            <br />
            <br />
            
            
            <asp:MultiView ID="MultiView1" runat="server" ActiveViewIndex="0" OnActiveViewChanged="MultiView1_ActiveViewChanged">
                <asp:View ID="View1" runat="server">
                    <div class="content">
                        <asp:Label ID="Label4" runat="server" Font-Size="XX-Large" Text="Manage Articles"></asp:Label>
                        <br />
                        <br />
                        <br />
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" DataSourceID="SqlDataSource1" Font-Size="Large" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                            <Columns>
                                <asp:BoundField DataField="Sno" HeaderText="Sno" InsertVisible="False" ReadOnly="True" SortExpression="Sno" />
                                <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                                <asp:BoundField DataField="Content" HeaderText="Content" SortExpression="Content" />
                            </Columns>
                            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
                            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FFF1D4" />
                            <SortedAscendingHeaderStyle BackColor="#B95C30" />
                            <SortedDescendingCellStyle BackColor="#F1E5CE" />
                            <SortedDescendingHeaderStyle BackColor="#93451F" />
                        </asp:GridView>
                        </div>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DB_InsuranceConnectionString %>" ProviderName="<%$ ConnectionStrings:DB_InsuranceConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [article]"></asp:SqlDataSource>
                    <br />
                    <br />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button3" runat="server" Font-Size="Large" Text="Submit Changes " ForeColor="#009900" />
                    <br />
                    <br />
                </asp:View>
                <asp:View ID="View2" runat="server">
                    <br />
                    <asp:Label ID="Label3" runat="server" Font-Size="XX-Large" Text="Add Articles"></asp:Label>
                    <br />
                    <br />
                    <br />
                    <br />
                    <asp:Label ID="Label1" runat="server" Font-Size="X-Large" Text="Title: "></asp:Label>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox1" runat="server" Font-Size="Medium" Height="46px" Width="285px" TextMode="MultiLine"></asp:TextBox>
                    <br />
                    <br />
                    <asp:Label ID="Label2" runat="server" Font-Size="X-Large" Text="Content: "></asp:Label>
&nbsp;<asp:TextBox ID="TextBox2" runat="server" Font-Size="Medium" Height="112px" Width="282px" TextMode="MultiLine"></asp:TextBox>
                    <br />
                    <br />
                    &nbsp;&nbsp;
                    <br />
                    <br />
                    <br />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button1" runat="server" Font-Size="Larger" Text="Submit" ForeColor="#009900" />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button2" runat="server" Font-Size="Larger" Text="Clear" ForeColor="Red" />
                </asp:View>
            </asp:MultiView>
            </div>
        </div>
            </div>
    </form>
</body>
</html>
